
(defpackage #:cipht/games/geometry-2d
  (:nicknames #:geom-2d #:geom)
  (:use #:cl #:alexandria #:anaphora)
  (:export
   #:+2PI+
#:APPLY-BOX-CORNERS-CCW
#:APPLY-POINT
#:APPLY-POINTS
#:BL-CORNER
#:BOX
#:POLYGON<-BOX
#:BOX-CONTAINS-BOX?
#:BOX-CONTAINS-POINT?
#:BOX-HEIGHT
#:BOX-WIDTH
#:BR-CORNER
#:CENTER-BOX-ON-POINT!
#:CLAMP-POINT
#:COPY-BOX
#:COPY-POINT
#:DISPLACE-POINT
#:HALF
#:ILERP
#:POINT
#:POINT<-POINT!
#:SCALE-BOX
#:SCALE-BOX-BY-POINT
#:SCALE-POINT
#:SCALE-POINT!
#:SCALE-POINT*
#:SINKF
#:TRANSLATE-BOX
#:TRANSLATE-BOX-TO
#:TRANSLATE-BOX-TO!
#:TRANSLATE-POINT
#:TRANSLATE-POINT!
#:TRANSLATE-POINT*
#:UL-CORNER
#:UNTRANSLATE-BOX
#:UNTRANSLATE-POINT
#:UNTRANSLATE-POINT!
#:UNTRANSLATE-POINT*
#:UR-CORNER
#:X-OF
#:Y-OF
   ))
